title: Apex Wave
description: Catch the Peak of Viral Trends. Data-driven newsroom.
baseurl: "/apex_wave"
url: "https://ggamesbgt.github.io"
markdown: kramdown

collections:
  agent_logs:
    output: true

  kpi_reports:
    output: true

  discussions:
    output: true
